### ISSUE TITLE
Private Board Access

### ISSUE THREAD

**Issue by darrkj** [jchrom/trelloR#23]
I was ale to use the code to access the public boards but ran into and issue with private boards. I followed the authorization steps got the token. I was then able to see the boards. After this though nothing else worked. Doing a request like get_board_cards results in Request failed [401]. From the wording of the docs 'One thing you can do immediately after obtaining ...', I was not sure if there were other steps. So the only thing you can do after getting the token is access the Private boards metadata but nothing more granular. I also cant find any further documentation. Is this an error or is there a next step I am missing?

**Comment by jchrom** [comment]
Hi @darrkj ,

are you feeding the token to the `get_` function? Example: `get_board_cards(board_id, my_token)`

**Comment by darrkj** [comment]
Yes, but I just noticed the issue in that function signature. The earlier calls to get_id_board take the URL but this one takes the board id. When I had passed the token I was getting an error, and then assumed that was not needed (dropbox api works like that) and not the issue. Problem is resolved by giving the function the id over the URL.

**Comment by jchrom** [comment]
Hi @darrkj ,
just released [v0.5](https://github.com/jchrom/trelloR/releases/tag/v0.5.0) - should allow you to use URLs where appropriate. Please upgrade if you can, and come back with any issues you find.
