### ISSUE TITLE
Modifying a card's power-up attributes

### ISSUE THREAD

**Issue by joranE** [jchrom/trelloR#25]
I suspect the answer to this might be "no", but I'm trying to figure out a way to add a card to a list while setting some attributes that are available as trello power-ups. Specifically, I have a custom field called "Requester" and the more complicated one is Box integration: can I create a card from R that automatically link the card to the RStudio project in Box?

Again, I'm guessing the answer to both is that I can't, but I just wanted to check.

**Comment by jchrom** [comment]
Thanks for the suggestion. I don't think I will ever be able to keep up with all the power ups out there. I'd be happy to review a pull request though.
