### ISSUE TITLE
"Unauthorized : expired token" error after any of the get functions

### ISSUE THREAD

**Issue by aedobbyn** [jchrom/trelloR#3]
Hi and thanks for your great work. I've been using the package with no issues until yesterday -- now I get a 401 error. I checked the Trello developer guide and my key and secret haven't changed. However, now the same code that was working,

`source("./api/trello_keys.R")`
`token <- trello_get_token(key, secret)`
`all_boards <- get_my_boards(token)`

gives me

`Error in get_flat(url = url, token = token, query = query) : 
  Client error: (401) Unauthorized : expired token`

 If you have any leads on this I'd much appreciate it!

**Comment by jchrom** [comment]
Hi and thanks! _Expired token_ means you have to authorize your app again. In your working directory, look for a hidden `.httr-oauth` file. Delete it. Then call `trello_get_token` again, and you will be prompted to authorize it in your browser. Tokens normally expire after 1 month I think (a default time interval set by Trello API itself).

Let me know if this helped!

**Comment by aedobbyn** [comment]
Yes, perfect! Thanks so much!

**Comment by aedobbyn** [comment]
Hey @jchrom thanks again for the great package. One question -- is there a way to re-authorize a token without going through the browser? I'd like to be able to host a script I run every day on a server. Thanks!

**Comment by jchrom** [comment]
Hi @aedobbyn - yes, that sounds nice. But I don't know enough to make it happen :/ I will look into it though. Furthermore, the issue #12 is related to this I think.

**Comment by aedobbyn** [comment]
@jchrom yes exactly. That RStudio article is very helpful, though, and might be a good way to go. If you were to make a change to the package, just allowing the user to provide a token if they know it and do the auth themselves would work in my case.

**Comment by jchrom** [comment]
@aedobbyn I have some leave coming up next week - let's see what I can do. Also, you are always welcome to make a pull request ;-)

**Comment by aedobbyn** [comment]
@jchrom I absolutely will if I come up with something! Cheers!
