### ISSUE TITLE
Cannot create token

### ISSUE THREAD

**Issue by samyoulmane** [jchrom/trelloR#30]
Hi !

I get the "Invalid return_url" error on my browser when I try to create a token for the first time using the `get_token()` function.

I'm using trelloR 0.6.0 and R 3.5.3 on macOS 10.15.

**Comment by jchrom** [comment]
Hi,

can you please try [this](https://github.com/jchrom/trelloR/issues/29#issuecomment-541321043)? It is the code for the get_token function, using functions from the [httr](https://github.com/r-lib/httr/issues) package. If this doesn't work for you, it means you have to ask the folks over at httr for advice.

Just in case it's useful, here is my `sessionInfo()` - perhaps updating some packages might help you? Especially httr_1.4.1 and perhaps curl_4.2 ? And maybe even R. As you can see I'm running Linux, which makes replicating bugs on Mac OS hard.

```
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: elementary OS 5.0 Juno (Ubuntu 18.04.2)

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=cs_CZ.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=cs_CZ.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=cs_CZ.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=cs_CZ.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] trelloR_0.6.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2        rstudioapi_0.10   magrittr_1.5     
 [4] tidyselect_0.2.5  R6_2.4.0          rlang_0.4.0      
 [7] httr_1.4.1        dplyr_0.8.3       tools_3.6.1      
[10] sessioninfo_1.1.1 cli_1.1.0         withr_2.1.2      
[13] askpass_1.1       openssl_1.4.1     assertthat_0.2.1 
[16] tibble_2.1.3      crayon_1.3.4      purrr_0.3.2      
[19] later_0.8.0       promises_1.0.1    curl_4.2         
[22] glue_1.3.1        compiler_3.6.1    pillar_1.4.2     
[25] jsonlite_1.6      httpuv_1.5.1      pkgconfig_2.0.3
```

**Comment by samyoulmane** [comment]
I updated R and all packages then I tried the code but it still doesn't work...
I will ask the issue at httr.
Thanks for your help !

**Comment by nickskalkin** [comment]
I also run into this problem. @samyoulmane did you find solution?

**Comment by nickskalkin** [comment]
And I don't think that it is somehow related to httr. Maybe trello changed something in their API? When I had Allowed Origins = * in this page https://trello.com/app-key - integration worked well. But now it is impossible to set wildcard there, and when I run `get_token` - I have the same error as @samyoulmane

**Comment by jchrom** [comment]
Hey @nickskalkin thanks for the suggestion! I also thought this could be the case, but with `http://localhost:1410` as allowed origin, it works just fine for me. What origin are you testing with?

EDIT: Also, are you on a Mac by any chance?

**Comment by nickskalkin** [comment]
Hey @jchrom! Yes, it helped me. Thanks a lot, mate! Should we add this to the documentation? I saw couple of people struggling with the same problem, maybe it would be better to mention `http://localhost:1410` in the docs

And yes, I'm on Mac :)

**Comment by jchrom** [comment]
Nice! @samyoulmane have you tried setting your Allowed Origin to `http://localhost:1410` ?

**Comment by navigate-cgalvao** [comment]
hi guys , I have the same problem .. but was not clear where I have to put the localhost ... :S

**Comment by jchrom** [comment]
@navigate-cgalvao I added some info about allowed origins to the updated docs, [see if it helps](https://jchrom.github.io/trelloR/articles/auth-access.html#getting-your-access-token).

**Comment by samyoulmane** [comment]
Hi @jchrom ! It worked fine for me when I set Allowed Origin to `http://localhost:1410`. Thank you !
