### ISSUE TITLE
Getting 401 Unauthorized errors

### ISSUE THREAD

**Issue by tanho63** [jchrom/trelloR#32]
Hiya! I know Atlassian just did stuff to Trello recently and now I'm getting 401 errors in the httr GET request. Where should I start looking in terms of debug?

It seems like I'm able to correctly call the httr call by passing `?key={trello_key}&token={trello_token}` appended to the URL, but the actual `GET(url={endpoint},token=token)` doesn't seem to be working. 

Will have to keep looking at this!

**Comment by jchrom** [comment]
Hi @tanho63,

you can start by telling me a bit more about what you did and how it failed. Output of `sessionInfo()` might also be useful.

In the meantime, I will tell you what I have done now to test:

1. Established authorized access as per [the vignette](https://jchrom.github.io/trelloR/articles/auth-access.html) - note the _allowed origins_ bit.
2. Accessed my private board and retrieved some data.

All worked for me. If you give me more details, I'm happy to help.

**Comment by tanho63** [comment]
Hey Jakub, thanks for getting back to me! 

The following code had worked for me up until ~last week or so. 

I have localhost:1410 set up as an allowed origin (how do I check that that is the correct port to open?)

![image](https://user-images.githubusercontent.com/38083823/80025348-7debc200-84ae-11ea-9847-09d840baec84.png)

and my code and error look like this:
```
> trello_token <- get_token(trello_key,trello_secret,appname = 'r-trello-app2',expiration = 'never')
# above works fine, returns a token object

> board_id <- get_my_boards() %>% 
+   filter(name == 'Automation Team') %>% 
+   pull(id)

GET URL:
https://api.trello.com/1/member/me/boards?limit=1000

  |==============================================================================================================| 100%
Request failed [401]. Retrying in 1.9 seconds...
  |==============================================================================================================| 100%
Request failed [401]. Retrying in 1.7 seconds...
  |==============================================================================================================| 100%
Error in get_url(url = url, token = token, response = response, on.error = on.error,  : 
  Unauthorized (HTTP 401).
```
I'm able to run `httr::GET("https://api.trello.com/1/member/me/boards?key={trello_key}&token={trello_token}")`, for what it's worth. 

![image](https://user-images.githubusercontent.com/38083823/80027298-8691c780-84b1-11ea-9e3b-c772d3f7c2c1.png)


SessionInfo: 
![image](https://user-images.githubusercontent.com/38083823/80025664-010d1800-84af-11ea-8655-af444c47adb2.png)

and I've tried uninstall/reinstall from github and getting a new token, which gets the token fine but does not correctly return a get_my_boards() call

**Comment by jchrom** [comment]
That's interesting!

IMHO your origin is fine, otherwise token creation would have failed in the first place. But you have a valid token which works when passed as a parameter.

Have you tried running the request like this?

```
token = trelloR::get_token(
  # create token as usual
)

httr::GET(
  url = "https://api.trello.com/1/member/me/boards",
  httr::config(token = token)
)
```

This is how trelloR does it - the whole token object gets passed via config. If this fails, perhaps the response will give us some clue.

**Comment by tanho63** [comment]
Hmm. that...works? 

![image](https://user-images.githubusercontent.com/38083823/80098564-1af43c80-853b-11ea-926b-322bde3e1bf6.png)

**Comment by jchrom** [comment]
Ha! Can you please look for your local .httr-oauth file (not sure if it is hidden on windows or not but it should exist in your project folder), delete it and then re-create your token?

**Comment by tanho63** [comment]
Hmm, that seemed to do it! Thanks for the assist :) 

Ideas on what caused that to happen?

**Comment by jchrom** [comment]
I think I know what to test next:

If multiple tokens are generated within the same project folder (because the original one expired or has been revoked), the old tokens persist in the .httr-oauth file. It is possible that the function that retrieves the token from cache gets confused and reads an obsolete token instead of the correct one.

**Comment by tanho63** [comment]
That's interesting - let me know if I can help at all! 

Thanks again for the assist, I'll close the issue now :)

**Comment by jchrom** [comment]
Hey @tanho63 

I have pushed some updates and bumped the version to 0.6.4, and it would be amazing if you can spare a few minutes to test. I have made a few changes to `get_token()`:

1. I added the `force.new` argument which, if set TRUE, will delete the locally cached token and trigger creation of a new one. This should resolve most problems.

2. The internal function that reads the cached tokens from disk will now always fetch the newest one.

Another big-ish change: I removed the few `dplyr` functions that were in use, which should make the package much lighter and install quicker. If you have `dplyr` or `tibble` installed, the functions will still return tibbles though.

I'd be grateful for any bug reports!

**Comment by tanho63** [comment]
Hey Jakub - had meant to reply to this earlier, changes work great for me :)
